# Generated by Django 2.1 on 2023-01-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0003_auto_20230121_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
