# Generated by Django 2.1 on 2023-01-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0004_remove_event_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
    ]
