# Generated by Django 2.1 on 2023-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0005_remove_event_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
