# Generated by Django 2.1 on 2023-01-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0009_auto_20230121_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
