# Generated by Django 2.1 on 2023-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0011_remove_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
