# Generated by Django 2.1 on 2023-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0013_auto_20230121_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(),
        ),
    ]
