# Generated by Django 2.1 on 2023-01-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
    ]
