# Generated by Django 2.1 on 2023-01-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0002_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info_url',
            field=models.CharField(default='asda', max_length=100),
            preserve_default=False,
        ),
    ]
