# Generated by Django 2.1 on 2023-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_list', '0003_event_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
