# Generated by Django 2.1 on 2023-01-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20230120_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start',
        ),
    ]
