# Generated by Django 2.1 on 2022-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.TextField(blank=True, null=True),
        ),
    ]
