# Generated by Django 4.1.7 on 2023-07-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idiomas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languague',
            old_name='languague',
            new_name='languagues',
        ),
    ]
