# Generated by Django 4.1.7 on 2023-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idiomas', '0002_rename_languague_languague_languagues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languague',
            old_name='languagues',
            new_name='languague',
        ),
    ]
