# Generated by Django 2.1 on 2022-12-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221216_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='content',
        ),
    ]
